stages:          # List of stages for jobs, and their order of execution
  - build
  - test


build-job:       
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  image: cypress/browsers   
  stage: test    
  script:
    - npm ci
    - npm install mochawesome
    - npx cypress run --reporter mochawesome
  artifacts:
    when: always
    paths:
      - mochawesome-report/**
      - cypress/screenshots/**/*.png
      - cypress/videos/**/*.mp4
    expire_in: 12 days

